# Generated by Django 5.0.1 on 2024-02-14 12:50

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Sportsman",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "chat_id",
                    models.PositiveBigIntegerField(
                        unique=True, verbose_name="Телеграм ID"
                    ),
                ),
                ("name", models.CharField(max_length=32, verbose_name="Имя")),
                (
                    "surname",
                    models.CharField(max_length=32, verbose_name="Фамилия"),
                ),
                (
                    "sheet_id",
                    models.PositiveBigIntegerField(verbose_name="ID листа"),
                ),
                (
                    "archive_sheet_id",
                    models.PositiveBigIntegerField(
                        verbose_name="ID архивного листа"
                    ),
                ),
                (
                    "is_send_morning",
                    models.BooleanField(
                        default=False,
                        verbose_name="Отправлено ли утренне уведомление",
                    ),
                ),
                (
                    "is_send_evening",
                    models.BooleanField(
                        default=False,
                        verbose_name="Отправлено ли вечернее уведомление",
                    ),
                ),
                (
                    "strava_keys",
                    models.TextField(
                        blank=True, null=True, verbose_name="Ключи API Strava"
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
            ],
            options={
                "verbose_name": "Спортсмен",
                "verbose_name_plural": "Спортсмены",
                "ordering": ("created_date",),
            },
        ),
    ]
