# Generated by Django 5.0.1 on 2024-03-13 22:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_rename_is_send_evening_sportsman_evening_reminder_sent_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sportsman",
            options={
                "ordering": ("-created_date",),
                "verbose_name": "Спортсмен",
                "verbose_name_plural": "Спортсмены",
            },
        ),
    ]
