# Generated by Django 5.0.1 on 2024-03-25 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_alter_sportsman_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Feeling",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.SmallIntegerField(
                        choices=[
                            (1, 1),
                            (2, 2),
                            (3, 3),
                            (4, 4),
                            (5, 5),
                            (6, 6),
                            (7, 7),
                            (8, 8),
                            (9, 9),
                            (10, 10),
                        ],
                        verbose_name="Оценка самочувствия",
                    ),
                ),
                ("sleep_hours", models.FloatField(verbose_name="Кол-во часов сна")),
                ("heart_rate", models.PositiveSmallIntegerField(verbose_name="Пульс")),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "sportsman",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feelings",
                        to="api.sportsman",
                    ),
                ),
            ],
            options={
                "verbose_name": "Самочувствие",
                "verbose_name_plural": "Самочувствие",
                "ordering": ("-created_date",),
            },
        ),
    ]
