START_COMMAND = "start"
REGISTRATION_COMMAND = "registration"
MORNING_REPORT_COMMAND = "morning_report"
REPORT_COMMAND = "report"
STRAVA_LOGIN = "authstrava"
SEND_WORKOUT_COMMAND = "sendworkout"
DELETE_COMMAND = "delete"
